<?php $this->headTitle('Default User Type | Setting ') ?>
<?php $defaultUserType = $this->defaultUserType ; ?>
<?php $selectedValue = $defaultUserType->getOptionValue() ?>
<?php $anotherValue = $selectedValue == "USER" ?  "ADMIN" : "USER";  ?>
<div class="col-md-12">
          <div class="box">

            <div class="box-header with-border">
              <h3 class="box-title">Site Settings | Default User Type</h3>
              <p class="alert alert-default">
              	<?php if($this->flashMessenger()->hasMessages()) : ?>
              	<?php foreach($this->flashMessenger()->getMessages() as $message)
		          	{
		          		echo $message;
		          	} 
		          ?>
		      <?php endif ?>
		      </p>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <div class="btn-group">
                  <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-wrench"></i></button>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                  </ul>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
            	<form method="POST">
            		<select name="default_user_type" class="form-control">
            			<option value="<?=$selectedValue?>"> <?= ucfirst(strtolower($selectedValue)) ?> </option>
            			<option value="<?=$anotherValue?>"> <?= ucfirst(strtolower($anotherValue)) ?> </option>
            		</select>
            		<br/>

            		<button type="submit" class="btn btn-success">Save </button>

            	</form>

            	
             
                <!-- /.col -->
              
              <!-- /.row -->
            </div>
            <!-- ./box-body -->
           
          </div>
          <!-- /.box -->
        </div>
