<?php $this->headTitle("Password Change") ?>

<div class="col-md-12">
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Change Password</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <div class="btn-group">
                  <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-wrench"></i></button>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                  </ul>
                </div>
                
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
               

                <form method="POST">
                    

                    <div class="form-group col-lg-8 col-md-8">
                    <label for="old_password">Old Password </label>
                    <input type="password" name="old_password" class="form-control" placeholder="Enter Old Password" id="old_password">
                    
                    </div>


                    <div class="form-group col-lg-8 col-md-8">
                    <label for="new_password_1"> New Password </label>
                    <input type="password" name="new_password_1" class="form-control" placeholder="Enter New Password" id="new_password_1">
                    
                    </div>

                    <div class="form-group col-lg-8 col-md-8">
                        <label for="new_password_2"> New Password Again </label>
                    <input type="password" name="new_password_2" class="form-control" placeholder="Enter New Password again" id="new_password_2">
                   
                    </div>

                    <div class="form-group col-lg-8 col-md-8">
                    <button class="btn btn-success" name="password_change" type="submit">
                        Change
                    </button>
                    </div>

                    </form>




                 </div>
            <!-- ./box-body -->
           
          </div>
          <!-- /.box -->
        </div>