<?= $this->partial('layout/header') ?>
<?php $currentUser = $this->auth()->getCurrentUser() ?>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
  <header class="main-header">
    <!-- Logo -->
    <a href="javascript::void(0)" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>U</b>M</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>User</b>Management</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          <li class="dropdown messages-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-envelope-o"></i>
              <span class="label label-success">4</span>
            </a>
           
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="/uploads/images/user/<?= $currentUser->getImage() ?>" class="user-image" alt="User Image">
              <span class="hidden-xs"><?= $currentUser->getName() ?></span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="/uploads/images/user/<?= $currentUser->getImage() ?>" class="img-circle" alt="User Image">

                <p>
                  <?= $currentUser->getName() ?> - 
                  <?= ucfirst(strtolower($currentUser->getUserType())) ?>
                  <small>Last Password Changed - <?= $currentUser->lastPasswordChangedDuration() ?></small>
                </p>
              </li>
              <!-- Menu Body -->
          
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="<?= $this->url('dashboard/profile') ?>" class="btn btn-default btn-flat">
                    <i class='fa fa-user'></i> Profile</a>
                </div>
                <div class="pull-right">
                  <a href="<?= $this->url('logout') ?>" class="btn btn-default btn-flat">
                    <i class='fa fa-sign-out'></i> Sign out</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="<?= $this->url('logout') ?>" data-toggle="tooltip" data-placement="top" title="Logout" data-title="Logout"><i class="fa fa-sign-out"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="/uploads/images/user/<?= $currentUser->getImage() ?>" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p><?= $currentUser->getName() ?></p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <li class="active treeview">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="<?=$this->url('index')?>"><i class="fa fa-home"></i> Home</a></li>
            <li><a href="<?=$this->url('dashboard/profile')?>"><i class="fa fa-user-o"></i> Profile</a></li>
            <li><a href="<?= $this->url('dashboard/passwordChange') ?>"><i class="fa fa-lock"></i> Password Change </a></li>
          </ul>
        </li>
        <?php if($currentUser->isAdmin()){  ?>
        
             <li class="treeview">
          <a href="#">
            <i class="fa fa-user-secret"></i> <span>Admin</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="<?=$this->url('user')?>"><i class="fa fa-users"></i> Users</a></li>
            <li><a href="<?=$this->url('admin/setting')?>"><i class="fa fa-cog"></i>Registration Settings</a></li>
          </ul>
        </li>
    <?php  }  ?>
        </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <br>
    <div class="container col-lg-12 col-md-12">
    <?php
     $flashMessenger = $this->flashMessenger();
     if($flashMessenger()->hasSuccessMessages())
     {
      $messages = $flashMessenger()->getSuccessMessages();
      foreach($messages as $message)
      {
        ?>

         <div class="alert alert-success alert-dismissible ">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
             <?= $message ?>
        </div>

      <?php }
     }

     if($flashMessenger->hasErrorMessages())
     {
      $messages = $flashMessenger()->getErrorMessages();
      foreach($messages as $message)
      {
        ?>

          <div class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
           <?= $message ?>
        </div>

      <?php }

     }
     ?>
   </div>

    <?= $this->content ?>
   

</div>
<!-- ./wrapper -->
<?= $this->partial('layout/footer') ?>
